/*
 * Port.c
 *
 *  Created on: Mar 4, 2022
 *      Author: Kishk
 */

#include "../../Services/Std_types.h"
#include "../../Services/Bit_utils.h"
#include "Port.h"
#include "avr/io.h"
#include "Port_prv.h"
#include "Port_cfg.h"

void Port_vidInit(void) {
#undef PORT_u8OUTPUT_LOW
#undef PORT_u8OUTPUT_HIGH
#undef PORT_u8INPUT_PULLUP
#define PORT_u8OUTPUT_LOW 		1
#define PORT_u8OUTPUT_HIGH		1
#define PORT_u8INPUT_PULLUP		0
DDRA =	CONC(PORT_u8MODE_PIN07,PORT_u8MODE_PIN06,PORT_u8MODE_PIN05,PORT_u8MODE_PIN04,PORT_u8MODE_PIN03,PORT_u8MODE_PIN02,PORT_u8MODE_PIN01,PORT_u8MODE_PIN00);
DDRB =	CONC(PORT_u8MODE_PIN15,PORT_u8MODE_PIN14,PORT_u8MODE_PIN13,PORT_u8MODE_PIN12,PORT_u8MODE_PIN11,PORT_u8MODE_PIN10,PORT_u8MODE_PIN09,PORT_u8MODE_PIN08);
DDRC =	CONC(PORT_u8MODE_PIN23,PORT_u8MODE_PIN22,PORT_u8MODE_PIN21,PORT_u8MODE_PIN20,PORT_u8MODE_PIN19,PORT_u8MODE_PIN18,PORT_u8MODE_PIN17,PORT_u8MODE_PIN16);
DDRD =	CONC(PORT_u8MODE_PIN31,PORT_u8MODE_PIN30,PORT_u8MODE_PIN29,PORT_u8MODE_PIN28,PORT_u8MODE_PIN27,PORT_u8MODE_PIN26,PORT_u8MODE_PIN25,PORT_u8MODE_PIN24);
#undef PORT_u8OUTPUT_LOW
#undef PORT_u8OUTPUT_HIGH
#undef PORT_u8INPUT_PULLUP
#define PORT_u8OUTPUT_LOW 		0
#define PORT_u8OUTPUT_HIGH		1
#define PORT_u8INPUT_PULLUP		1
PORTA =	CONC(PORT_u8MODE_PIN07,PORT_u8MODE_PIN06,PORT_u8MODE_PIN05,PORT_u8MODE_PIN04,PORT_u8MODE_PIN03,PORT_u8MODE_PIN02,PORT_u8MODE_PIN01,PORT_u8MODE_PIN00);
PORTB =	CONC(PORT_u8MODE_PIN15,PORT_u8MODE_PIN14,PORT_u8MODE_PIN13,PORT_u8MODE_PIN12,PORT_u8MODE_PIN11,PORT_u8MODE_PIN10,PORT_u8MODE_PIN09,PORT_u8MODE_PIN08);
PORTC =	CONC(PORT_u8MODE_PIN23,PORT_u8MODE_PIN22,PORT_u8MODE_PIN21,PORT_u8MODE_PIN20,PORT_u8MODE_PIN19,PORT_u8MODE_PIN18,PORT_u8MODE_PIN17,PORT_u8MODE_PIN16);
PORTD =	CONC(PORT_u8MODE_PIN31,PORT_u8MODE_PIN30,PORT_u8MODE_PIN29,PORT_u8MODE_PIN28,PORT_u8MODE_PIN27,PORT_u8MODE_PIN26,PORT_u8MODE_PIN25,PORT_u8MODE_PIN24);
#undef PORT_u8OUTPUT_LOW
#undef PORT_u8OUTPUT_HIGH
#define PORT_u8OUTPUT_LOW		2
#define PORT_u8OUTPUT_HIGH		3

}

Port_tenuErrorStatus Port_enuSetPinDirection(u8 Copy_u8PinNum,
		u8 Copy_u8PinDirection) {
	/*DECLARE RETURN STATUS*/
	Port_tenuErrorStatus LOC_enuReturnStatus = Port_enuOk;
	/*DECLARE VARIABLE TO STORE PIN NUMBER & PORT NUMBER*/
	u8 LOC_u8PinNum = 0;
	u8 LOC_u8PortNum = 0;
	/*CHECK IF THE ENTERED PIN NUMBER IS INVALID*/
	if (Copy_u8PinNum > PORT_u8MAX_PINS) {
		/*ASSIGN ERROR INTO RETURN STATUS*/
		LOC_enuReturnStatus = Port_enuPinError;
	}
	/*CHECK IF THE ENTERED PIN DIRECTION IS INVALID BIGGER THAN '1' */
	else if (Copy_u8PinDirection > PORT_u8OUTPUT) {
		/*ASSIGN ERROR INTO RETURN STATUS*/
		LOC_enuReturnStatus = Port_enuDirectionError;
	} else {
		/*CALCULATE PIN NUMBER*/
		LOC_u8PinNum = Copy_u8PinNum % PORT_u8REGISTER_SIZE;
		/*CALCULATE PORT NUMBER*/
		LOC_u8PortNum = Copy_u8PinNum / PORT_u8REGISTER_SIZE;
		/*SWITCH CASE TO CHECK PORT*/
		switch (LOC_u8PortNum) {
		/*CASE PORT A*/
		case PORT_u8PORTA: {
			/*CHECK IF THE PIN DIRECTION OUTPUT*/
			if (Copy_u8PinDirection == PORT_u8OUTPUT) {
				/*SET BIT IN DDRA REGISTER*/
				SET_BIT(DDRA, LOC_u8PinNum);
			} else {
				/*CLEAR BIT IN DDRA REGISTER*/
				CLR_BIT(DDRA, LOC_u8PinNum);
			}
			/*BREAK OUT CASE*/
			break;
		}
			/*CASE PORT B*/
		case PORT_u8PORTB: {
			/*CHECK IF THE PIN DIRECTION OUTPUT*/
			if (Copy_u8PinDirection == PORT_u8OUTPUT) {
				/*SET BIT IN DDRA REGISTER*/
				SET_BIT(DDRB, LOC_u8PinNum);
			} else {
				/*CLEAR BIT IN DDRA REGISTER*/
				CLR_BIT(DDRB, LOC_u8PinNum);
			}
			/*BREAK OUT CASE*/
			break;
		}
			/*CASE PORT C*/
		case PORT_u8PORTC: {
			/*CHECK IF THE PIN DIRECTION OUTPUT*/
			if (Copy_u8PinDirection == PORT_u8OUTPUT) {
				/*SET BIT IN DDRA REGISTER*/
				SET_BIT(DDRC, LOC_u8PinNum);
			} else {
				/*CLEAR BIT IN DDRA REGISTER*/
				CLR_BIT(DDRC, LOC_u8PinNum);
			}
			/*BREAK OUT CASE*/
			break;
		}
			/*CASE PORT D*/
		case PORT_u8PORTD: {
			/*CHECK IF THE PIN DIRECTION OUTPUT*/
			if (Copy_u8PinDirection == PORT_u8OUTPUT) {
				/*SET BIT IN DDRA REGISTER*/
				SET_BIT(DDRA, LOC_u8PinNum);
			} else {
				/*CLEAR BIT IN DDRA REGISTER*/
				CLR_BIT(DDRA, LOC_u8PinNum);
			}
			/*BREAK OUT CASE*/
			break;
		}
		default: {

		}
		}
	}
	/*RETURN ERROR STATUS*/
	return LOC_enuReturnStatus;

}
Port_tenuErrorStatus Port_enuSetPinMode(u8 Copy_u8PinNum, u8 Copy_u8PinMode) {
	/*DECLARE RETURN STATUS*/
	Port_tenuErrorStatus LOC_enuReturnStatus = Port_enuOk;
	/*DECLARE VARIABLE TO STORE PIN NUMBER & PORT NUMBER*/
	u8 LOC_u8PinNum = 0;
	u8 LOC_u8PortNum = 0;
	/*CHECK IF THE ENTERED PIN NUMBER IS INVALID*/
	if (Copy_u8PinNum > PORT_u8MAX_PINS) {
		/*ASSIGN ERROR INTO RETURN STATUS*/
		LOC_enuReturnStatus = Port_enuPinError;
	}
	/*CHECK IF THE ENTERED PIN MODE IS INVALID BIGGER THAN '3' */
	else if (Copy_u8PinMode > PORT_u8OUTPUT_HIGH) {
		/*ASSIGN ERROR INTO RETURN STATUS*/
		LOC_enuReturnStatus = Port_enuModeError;
	} else {
		/*CALCULATE PIN NUMBER*/
		LOC_u8PinNum = Copy_u8PinNum % PORT_u8REGISTER_SIZE;
		/*CALCULATE PORT NUMBER*/
		LOC_u8PortNum = Copy_u8PinNum / PORT_u8REGISTER_SIZE;
		/*SWITCH CASE TO CHECK PORT*/
		switch (LOC_u8PortNum) {
		/*CASE PORT A*/
		case PORT_u8PORTA: {
			/*SWITCH CASE TO CHECK PIN MODE */
			switch (Copy_u8PinMode) {
			/*CASE INPUT FLOATING*/
			case PORT_u8INPUT_FLOATING: {
				/*CLEAR DATA DIRCTION REGISTER TO MAKE IT INPUT*/
				CLR_BIT(DDRA, LOC_u8PinNum);
				/*CLEAR PORTA BIT TO MAKE IT FLOATING*/
				CLR_BIT(PORTA, LOC_u8PinNum);
				/*PORT_u8INPUT_FLOATING BREAK*/
				break;
			}
				/*CASE INPUT PULLUP*/
			case PORT_u8INPUT_PULLUP: {
				/*CLEAR DATA DIRCTION REGISTER TO MAKE IT INPUT*/
				CLR_BIT(DDRA, LOC_u8PinNum);
				/*SET PORTA BIT TO ACTIVE PULLUP RESISTOR*/
				SET_BIT(PORTA, LOC_u8PinNum);
				/*PORT_u8INPUT_PULLUP BREAK*/
				break;
			}
				/*CASE OUTPUT LOW*/
			case PORT_u8OUTPUT_LOW: {
				/*SET DATA DIRCTION REGISTER TO MAKE IT OUTPUT*/
				SET_BIT(DDRA, LOC_u8PinNum);
				/*CLEAR PORTA BIT TO MAKE IT OUTPUT LOW*/
				CLR_BIT(PORTA, LOC_u8PinNum);
				/*PORT_u8OUTPUT_LOW BREAK*/
				break;
			}
				/*CASE OUTPUT HIGH*/
			case PORT_u8OUTPUT_HIGH: {
				/*SET DATA DIRCTION REGISTER TO MAKE IT OUTPUT*/
				SET_BIT(DDRA, LOC_u8PinNum);
				/*SET PORTA BIT TO MAKE IT OUTPUT HIGH*/
				SET_BIT(PORTA, LOC_u8PinNum);
				/*PORT_u8OUTPUT_HIGH BREAK*/
				break;
			}
			}

			/*BREAK OUT CASE*/
			break;
		}
			/*CASE PORT B*/
		case PORT_u8PORTB: {
			/*CHECK IF THE PIN DIRECTION OUTPUT*/
			/*SWITCH CASE TO CHECK PIN MODE */
			switch (Copy_u8PinMode) {
			/*CASE INPUT FLOATING*/
			case PORT_u8INPUT_FLOATING: {
				/*CLEAR DATA DIRCTION REGISTER TO MAKE IT INPUT*/
				CLR_BIT(DDRB, LOC_u8PinNum);
				/*CLEAR PORTA BIT TO MAKE IT FLOATING*/
				CLR_BIT(PORTB, LOC_u8PinNum);
				/*PORT_u8INPUT_FLOATING BREAK*/
				break;
			}
				/*CASE INPUT PULLUP*/
			case PORT_u8INPUT_PULLUP: {
				/*CLEAR DATA DIRCTION REGISTER TO MAKE IT INPUT*/
				CLR_BIT(DDRB, LOC_u8PinNum);
				/*SET PORTA BIT TO ACTIVE PULLUP RESISTOR*/
				SET_BIT(PORTB, LOC_u8PinNum);
				/*PORT_u8INPUT_PULLUP BREAK*/
				break;
			}
				/*CASE OUTPUT LOW*/
			case PORT_u8OUTPUT_LOW: {
				/*SET DATA DIRCTION REGISTER TO MAKE IT OUTPUT*/
				SET_BIT(DDRB, LOC_u8PinNum);
				/*CLEAR PORTA BIT TO MAKE IT OUTPUT LOW*/
				CLR_BIT(PORTB, LOC_u8PinNum);
				/*PORT_u8OUTPUT_LOW BREAK*/
				break;
			}
				/*CASE OUTPUT HIGH*/
			case PORT_u8OUTPUT_HIGH: {
				/*SET DATA DIRCTION REGISTER TO MAKE IT OUTPUT*/
				SET_BIT(DDRB, LOC_u8PinNum);
				/*SET PORTA BIT TO MAKE IT OUTPUT HIGH*/
				SET_BIT(PORTB, LOC_u8PinNum);
				/*PORT_u8OUTPUT_HIGH BREAK*/
				break;
			}
			}
			/*BREAK OUT CASE*/
			break;
		}
			/*CASE PORT C*/
		case PORT_u8PORTC: {
			/*CHECK IF THE PIN DIRECTION OUTPUT*/
			/*SWITCH CASE TO CHECK PIN MODE */
			switch (Copy_u8PinMode) {
			/*CASE INPUT FLOATING*/
			case PORT_u8INPUT_FLOATING: {
				/*CLEAR DATA DIRCTION REGISTER TO MAKE IT INPUT*/
				CLR_BIT(DDRC, LOC_u8PinNum);
				/*CLEAR PORTA BIT TO MAKE IT FLOATING*/
				CLR_BIT(PORTC, LOC_u8PinNum);
				/*PORT_u8INPUT_FLOATING BREAK*/
				break;
			}
				/*CASE INPUT PULLUP*/
			case PORT_u8INPUT_PULLUP: {
				/*CLEAR DATA DIRCTION REGISTER TO MAKE IT INPUT*/
				CLR_BIT(DDRC, LOC_u8PinNum);
				/*SET PORTA BIT TO ACTIVE PULLUP RESISTOR*/
				SET_BIT(PORTC, LOC_u8PinNum);
				/*PORT_u8INPUT_PULLUP BREAK*/
				break;
			}
				/*CASE OUTPUT LOW*/
			case PORT_u8OUTPUT_LOW: {
				/*SET DATA DIRCTION REGISTER TO MAKE IT OUTPUT*/
				SET_BIT(DDRC, LOC_u8PinNum);
				/*CLEAR PORTA BIT TO MAKE IT OUTPUT LOW*/
				CLR_BIT(PORTC, LOC_u8PinNum);
				/*PORT_u8OUTPUT_LOW BREAK*/
				break;
			}
				/*CASE OUTPUT HIGH*/
			case PORT_u8OUTPUT_HIGH: {
				/*SET DATA DIRCTION REGISTER TO MAKE IT OUTPUT*/
				SET_BIT(DDRC, LOC_u8PinNum);
				/*SET PORTA BIT TO MAKE IT OUTPUT HIGH*/
				SET_BIT(PORTC, LOC_u8PinNum);
				/*PORT_u8OUTPUT_HIGH BREAK*/
				break;
			}
			}
			/*BREAK OUT CASE*/
			break;
		}
			/*CASE PORT D*/
		case PORT_u8PORTD: {
			/*SWITCH CASE TO CHECK PIN MODE */
			switch (Copy_u8PinMode) {
			/*CASE INPUT FLOATING*/
			case PORT_u8INPUT_FLOATING: {
				/*CLEAR DATA DIRCTION REGISTER TO MAKE IT INPUT*/
				CLR_BIT(DDRD, LOC_u8PinNum);
				/*CLEAR PORTA BIT TO MAKE IT FLOATING*/
				CLR_BIT(PORTD, LOC_u8PinNum);
				/*PORT_u8INPUT_FLOATING BREAK*/
				break;
			}
				/*CASE INPUT PULLUP*/
			case PORT_u8INPUT_PULLUP: {
				/*CLEAR DATA DIRCTION REGISTER TO MAKE IT INPUT*/
				CLR_BIT(DDRD, LOC_u8PinNum);
				/*SET PORTA BIT TO ACTIVE PULLUP RESISTOR*/
				SET_BIT(PORTD, LOC_u8PinNum);
				/*PORT_u8INPUT_PULLUP BREAK*/
				break;
			}
				/*CASE OUTPUT LOW*/
			case PORT_u8OUTPUT_LOW: {
				/*SET DATA DIRCTION REGISTER TO MAKE IT OUTPUT*/
				SET_BIT(DDRD, LOC_u8PinNum);
				/*CLEAR PORTA BIT TO MAKE IT OUTPUT LOW*/
				CLR_BIT(PORTD, LOC_u8PinNum);
				/*PORT_u8OUTPUT_LOW BREAK*/
				break;
			}
				/*CASE OUTPUT HIGH*/
			case PORT_u8OUTPUT_HIGH: {
				/*SET DATA DIRCTION REGISTER TO MAKE IT OUTPUT*/
				SET_BIT(DDRD, LOC_u8PinNum);
				/*SET PORTA BIT TO MAKE IT OUTPUT HIGH*/
				SET_BIT(PORTD, LOC_u8PinNum);
				/*PORT_u8OUTPUT_HIGH BREAK*/
				break;
			}
			}
			/*BREAK OUT CASE*/
			break;
		}
		}
	}
	/*RETURN ERROR STATUS*/
	return LOC_enuReturnStatus;
}
