/*
 * Adc_cfg.h
 *
 *  Created on: Mar 25, 2022
 *      Author: Kishk
 */

#ifndef MCAL_ADC_ADC_CFG_H_
#define MCAL_ADC_ADC_CFG_H_

/*
 * OPTIONS:-
 * 1- ADC_u8REF_SELC_AREF
 * 2- ADC_u8REF_SELC_AVCC
 * 3- ADC_u8REF_SELC_256MV
 * */

#define ADC_u8REFERENCE_SELECTION		ADC_u8REF_SELC_AVCC

/*
 * OPTIONS:-
 * 1- ADC_u8AJUSTMENT_LEFT
 * 2- ADC_u8AJUSTMENT_RIGHT
 * */
#define ADC_u8ADJUSTMENT_RESULT			ADC_u8AJUSTMENT_RIGHT

/*
 * OPTIONS:-
 * 1- ADC_u8AUTO_TRIG_DISABLE
 * 2- ADC_u8AUTO_TRIG_ENABLE
 * */

#define ADC_u8AUTO_TRIGGER				ADC_u8AUTO_TRIG_DISABLE

/*
 * OPTIONS:-
 * 1- ADC_u8INTERRUPT_DISABLE
 * 2- ADC_u8INTERRUPT_ENABLE
 * */

#define ADC_u8INTERRUPT					ADC_u8INTERRUPT_DISABLE

/*
 * OPTIONS:-
 * 1- ADC_u8PRESCALLER_DIV_BY_2
 * 2- ADC_u8PRESCALLER_DIV_BY_4
 * 4- ADC_u8PRESCALLER_DIV_BY_8
 * 3- ADC_u8PRESCALLER_DIV_BY_16
 * 5- ADC_u8PRESCALLER_DIV_BY_32
 * 6- ADC_u8PRESCALLER_DIV_BY_64
 * 7- ADC_u8PRESCALLER_DIV_BY_128
 * */

#define ADC_u8PRESCALLER			ADC_u8PRESCALLER_DIV_BY_128

/*
 * OPTIONS:-
 * 1- ADC_u8TRIG_SRC_FREE_RUNNING_MODE
 * 2- ADC_u8TRIG_SRC_ANALOG_COMPARATOR
 * 4- ADC_u8TRIG_SRC_EXTERNAL_IRQ0
 * 3- ADC_u8TRIG_SRC_TIMER0_CMPRMATCH
 * 5- ADC_u8TRIG_SRC_TIMER0_OVRFLW
 * 6- ADC_u8TRIG_SRC_TIMER_CMPRMATCHB
 * 7- ADC_u8TRIG_SRC_TIMER1_OVRFLW
 * 8- ADC_u8TRIG_SRC_TIMER1_CAPEVENT
 * */
#define ADC_u8AUTO_TRIGGER_SOURCE	ADC_u8TRIG_SRC_FREE_RUNNING_MODE

#endif /* MCAL_ADC_ADC_CFG_H_ */
